### ISSUE TITLE
Issue with DKMS and multiple kernel-header packages installed

### ISSUE THREAD

**Issue by cf-sewe** [bodgit/puppet-zfs#26] opened 2019-11-29 20:43 UTC
System: CentOS 7.7

Puppet profile zfs module invocation:
```
    class { '::zfs':
      kmod_type   => 'dkms',
      zfs_arc_max => to_bytes('16 G'),
      zfs_arc_min => to_bytes('1 G'),
    }
```

When updating the kernel via regular yum update, the system will have multiple versions of kernel-header installed at the end:

```
# rpm -qa kernel-devel
kernel-devel-3.10.0-1062.4.1.el7.x86_64
kernel-devel-3.10.0-1062.4.3.el7.x86_64
```

This leads to a failure with puppet using the zfs module:

```
Error: Could not update: Failed to update to version 3.10.0-1062.4.3.el7.x86_64, got version 3.10.0-1062.4.1.el7; 3.10.0-1062.4.3.el7 instead
Error: /Stage[main]/Zfs::Install/Package[kernel-devel]/ensure: change from '3.10.0-1062.4.1.el7; 3.10.0-1062.4.3.el7' to '3.10.0-1062.4.3.el7.x86_64' failed: Could not update: Failed to update to version 3.10.0-1062.4.3.el7.x86_64, got version 3.10.0-1062.4.1.el7; 3.10.0-1062.4.3.el7 instead (corrective)
```

This is problematic, because the puppet run is failing until I remove the older kernel-devel package manually from all systems.

**Comment by bodgit** [comment] 2019-12-01 11:43
Interesting. I changed the kernel-devel package ensure to the version of the kernel that is actually running rather than just `present` otherwise if you're not running the latest kernel, it would install the kernel-devel package for the newest kernel and you wouldn't then have working ZFS until you reboot.

It feels a little bit like a bug in Puppet here that it's not handling multiple versions of the same package very well.

**Comment by cf-sewe** [comment] 2019-12-02 08:07
Thanks a lot for your fast feedbeck. Your solution sounds good. Actually for older kernels the DKMS modules should already exist because the kernel upgrade procedure normally ensures this.

And fully agree in regard to the potential Puppet bug/issue in regard to ensure_packages

**Comment by bodgit** [comment] 2019-12-16 11:18
I'm not sure I can fix this any other way apart from replacing the `package` resource with a hacky `exec`, I've found reported Puppet issues for this problem where the resolution is basically "won't fix" as they don't want to admit that you can have multiple versions of the same package installed.

I'll push something shortly.

**Comment by bodgit** [comment] 2019-12-17 10:09
So actually, the following should work:
```puppet
package { "kernel-devel-${facts['kernelrelease']}":
  ensure => present,
}
```
instead of
```puppet
package { "kernel-devel":
  ensure => $facts['kernelrelease'],
}
```
Bit of a hack as I think it's working by fluke rather than by design but it's better than an `exec`.

**Comment by cf-sewe** [comment] 2019-12-17 10:12
I checked, the fact is present on my system. That should work!
There might be an issue when you recently updated the kernel and did not reboot yet.

Anyway - I am considering now to change back to KABI tracking mod, also this requires the "footprint" on the server because it doesn't need to compile the ZFS module. The only issue is then with Distro version updates...  ZOL is still not as robust as it should be...

**Closed as completed** 2019-12-18 23:25 UTC
Labels: bug

**Comment by bodgit** [comment] 2019-12-19 09:58
> There might be an issue when you recently updated the kernel and did not reboot yet.

This is true, I'm not sure what I can realistically do about that.

I've uploaded v2.2.7 to the forge which should hopefully fix this issue, sorry for breaking it. I'm still waiting for a new release of `stahnma/epel` which supports EL8 and then I can fix that too.

**Comment by cf-sewe** [comment] 2019-12-19 10:00
Thank you, for your super nice support 🥇 
Have a nice holiday time!
